ClosDotNet/Controllers/BusinessController.cs
namespace ClosDotNet.Controllers
{
    using ClosDotNet.Domain.Business;
    using ClosDotNet.Domain.Customer;
    using ClosDotNet.Helper;
    using ClosDotNet.Mapper;
    using ClosDotNet.Models;
    using ClosDotNet.Resources.Resources;
    using Common.Logging;
    using System;
    using System.Web.Mvc;

    [Authorize]
    public class BusinessController : CommonController
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(BusinessController));

        public IBusinessBO BusinessBO { get; set; }
        public IMapper BusinessMapper { get; set; }

        public ActionResult ViewBusiness()
        {
            ClearSessionData();

            ICustomerVO sessionCustomer = (ICustomerVO)Session["SessionCustomer"];
            if (sessionCustomer != null)
            {
                IBusinessVO business = BusinessBO.RetrieveBusinessByCustomerId(sessionCustomer.Id);
                if (business == null)
                {
                    business = new BusinessVO();
                }
                Session["SessionBusiness"] = business;

                BusinessViewModel model = (BusinessViewModel) BusinessMapper.Map(
                    business, typeof(IBusinessVO), typeof(BusinessViewModel));
                if (string.IsNullOrEmpty(model.CurrentPaidUpCapitalCurrency))
                {
                    model.CurrentPaidUpCapitalCurrency = Constants.GetEnumDescription(Currency.SingaporeDollar);
                }

                // Needed to do this so that the client validation will not trigger.
                TempData["BusinessDetailModel"] = model;
            }

            return RedirectToAction("ViewBusinessDetails");
        }

        public ActionResult ViewBusinessDetails()
        {
            BusinessViewModel model = (BusinessViewModel) TempData["BusinessDetailModel"];

            ViewBag.CurrencyList = GetDropdownList(CodeSetCode.CURRENCY, BusinessMapper);
            ViewBag.DisplayMode = DisplayMode.Edit;
            if (User.IsInRole(Constants.GetEnumDescription(UserRole.CA)))
            {
                ViewBag.DisplayMode = DisplayMode.View;
            }
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult SaveBusiness(BusinessViewModel model)
        {
            try
            {
                IBusinessVO business = (BusinessVO)
                    BusinessMapper.Map(model, typeof(BusinessViewModel), typeof(BusinessVO));
                business.LastUpdateBy = User.Identity.Name;

                ICustomerVO sessionCustomer = (ICustomerVO)Session["SessionCustomer"];
                business.Customer = sessionCustomer;

                if (business.Id == 0)
                {
                    business = BusinessBO.CreateBusiness(business);
                }
                else
                {
                    IBusinessVO sessionBusiness = (IBusinessVO)Session["SessionBusiness"];
                    business = BusinessBO.UpdateBusiness(sessionBusiness, business);
                }

                model = (BusinessViewModel)
                    BusinessMapper.Map(business, typeof(IBusinessVO), typeof(BusinessViewModel));

                Session["SessionBusiness"] = business;
                TempData["MessageType"] = MessageType.Success;
                TempData["MessageDescription"] = CommonResources.MessageSaveSuccess;
            }
            catch (Exception exception)
            {
                Logger.Debug("Exception encountered: " + exception.StackTrace);

                TempData["MessageType"] = MessageType.Error;
                TempData["MessageDescription"] = CommonResources.MessageSaveError + exception.Message;
            }

            TempData["BusinessDetailModel"] = model;
            return RedirectToAction("ViewBusinessDetails");
        }

        #region Utility Methods
        private void ClearSessionData()
        {
            Session["SessionBusiness"] = null;
        }
        #endregion Utility Methods
    }
}

ClosDotNet/Controllers/CustomerController.cs
namespace ClosDotNet.Controllers
{
    using ClosDotNet.Domain.CodeSet;
    using ClosDotNet.Domain.Customer;
    using ClosDotNet.Domain.User;
    using ClosDotNet.Filters;
    using ClosDotNet.Helper;
    using ClosDotNet.Mapper;
    using ClosDotNet.Models;
    using ClosDotNet.Resources.Resources;
    using Common.Logging;
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    [Authorize]
    public class CustomerController : CommonController
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(CustomerController));

        public IUserBO UserBO { get; set; }
        public ICustomerBO CustomerBO { get; set; }
        public IMapper CustomerMapper { get; set; }

        public CustomerController()
        {
        }

        #region Search
        public ActionResult Search()
        {
            Session.Clear();
            TempData.Clear();

            ViewBag.IdTypeList = GetDropdownList(CodeSetCode.ID_TYPE, CustomerMapper);
            ViewBag.CountryList = GetDropdownList(CodeSetCode.COUNTRY, CustomerMapper);

            return View(new SearchViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchByCustomerName(SearchViewModel searchModel)
        {
            Logger.Debug("SearchByCustomerName|Search customer by name: " 
                + searchModel.SearchCustomerName.CustomerName);

            IList<ICustomerVO> customerList = 
                CustomerBO.RetrieveCustomersByName(searchModel.SearchCustomerName.CustomerName);
            Logger.Debug("SearchByCustomerName|Search Result: " + (customerList != null ? customerList.Count : 0));

            TempData["SearchResultList"] = customerList;
            return RedirectToAction("ViewSearchResult");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchByCifNumber(SearchViewModel searchModel)
        {
            Logger.Debug("SearchByCifNumber|Search CIF number: " + searchModel.SeachCifNumber.CifNumber);
            IList<ICustomerVO> customerList = new List<ICustomerVO>();

            ICustomerVO customer = CustomerBO.RetrieveCustomerByCifNumber(searchModel.SeachCifNumber.CifNumber);
            if (customer != null)
            {
                customerList.Add(customer);
            }

            Logger.Debug("SearchByCifNumber|Search Result: " + (customerList != null ? customerList.Count : 0));

            TempData["SearchResultList"] = customerList;
            return RedirectToAction("ViewSearchResult");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchByIdCombination(SearchViewModel searchModel)
        {
            Logger.Debug("SearchByIdCombination|Search ID combination: " +
                searchModel.SeachIdCombination.IdType + "|" +
                searchModel.SeachIdCombination.IdNumber + "|" +
                searchModel.SeachIdCombination.IdIssuedCountry);
            IList<ICustomerVO> customerList = new List<ICustomerVO>();

            ICustomerVO customer = CustomerBO.RetrieveCustomerByIdCombination(
                searchModel.SeachIdCombination.IdType,
                searchModel.SeachIdCombination.IdNumber,
                searchModel.SeachIdCombination.IdIssuedCountry);
            if (customer != null)
            {
                customerList.Add(customer);
            }

            Logger.Debug("SearchByIdCombination|Search Result: " + (customerList != null ? customerList.Count : 0));

            TempData["SearchResultList"] = customerList;
            return RedirectToAction("ViewSearchResult");
        }

        public ActionResult ViewSearchResult()
        {
            IList<ICustomerVO> customerList = (IList<ICustomerVO>) TempData["SearchResultList"];
            IEnumerable<SearchResultViewModel> model = (IEnumerable<SearchResultViewModel>)
                CustomerMapper.Map(customerList,
                    typeof(IList<ICustomerVO>), typeof(IEnumerable<SearchResultViewModel>));

            return View(model);
        }
        #endregion Search

        #region Detail
        [Button(ButtonName = "PrepareCreateCompany")]
        [ActionName("PrepareCreateCustomer")]
        public ActionResult PrepareCreateCompanyCustomer()
        {
            ICompanyCustomerVO customer = new CompanyCustomerVO();
            // Default values for new customer.
            customer.IdIssuedCountry = new CountryVO() { Code = Constants.GetEnumDescription(Country.Singapore) };
            customer.CustomerType = Constants.GetEnumDescription(CustomerType.Corporate);
            customer.RelationshipManager = UserBO.RetrieveUserByLoginId(User.Identity.Name);
            customer.AddressList = new List<IAddressVO>();
            customer.AddressList.Add(new AddressVO() { AddressType = Constants.GetEnumDescription(AddressType.Business) });
            customer.AddressList.Add(new AddressVO() { AddressType = Constants.GetEnumDescription(AddressType.Mailing) });

            Session["SessionCustomer"] = customer;
            return RedirectToAction("ViewCompanyDetails");
        }

        [Button(ButtonName = "PrepareCreateIndividual")]
        [ActionName("PrepareCreateCustomer")]
        public ActionResult PrepareCreateIndividualCustomer()
        {
            IIndividualCustomerVO customer = new IndividualCustomerVO();
            // Default values for new customer.
            customer.IdIssuedCountry = new CountryVO() { Code = Constants.GetEnumDescription(Country.Singapore) };
            customer.CustomerType = Constants.GetEnumDescription(CustomerType.Individual);
            customer.RelationshipManager = UserBO.RetrieveUserByLoginId(User.Identity.Name);
            customer.AddressList = new List<IAddressVO>();
            customer.AddressList.Add(new AddressVO() { AddressType = Constants.GetEnumDescription(AddressType.Home) });
            customer.AddressList.Add(new AddressVO() { AddressType = Constants.GetEnumDescription(AddressType.Mailing) });

            Session["SessionCustomer"] = customer;
            return RedirectToAction("ViewIndividualDetails");
        }

        public ActionResult ViewCustomer(int? customerId, string customerType)
        {
            Logger.Debug("ViewCustomer|Selected Customer ID: " + customerId);

            if (customerId != null)
            {
                if (Constants.GetEnumDescription(CustomerType.Individual).Equals(customerType))
                {
                    Session["SessionCustomer"] = 
                        (IIndividualCustomerVO)CustomerBO.RetrieveIndividualCustomer(customerId ?? default(int));
                }
                else
                {
                    Session["SessionCustomer"] =
                        (ICompanyCustomerVO)CustomerBO.RetrieveCompanyCustomer(customerId ?? default(int));
                }
            }
            
            if (Constants.GetEnumDescription(CustomerType.Individual).Equals(customerType))
            {
                return RedirectToAction("ViewIndividualDetails");
            }   

            return RedirectToAction("ViewCompanyDetails");
        }

        public ActionResult ViewCompanyDetails()
        {
            CustomerViewModel model = (CompanyCustomerViewModel) TempData["CustomerDetailModel"];
            if (model == null)
            {
                ICustomerVO customer = (ICompanyCustomerVO)Session["SessionCustomer"];
                if (customer != null)
                {
                    model = (CompanyCustomerViewModel)
                        CustomerMapper.Map(customer, typeof(ICompanyCustomerVO), typeof(CompanyCustomerViewModel));
                    TempData["CustomerDetailModel"] = model;
                }
            }

            PrepareOptionsList(CustomerType.Corporate);            
            ViewBag.DisplayMode = DisplayMode.Edit;
            if (User.IsInRole(Constants.GetEnumDescription(UserRole.CA)))
            {
                ViewBag.DisplayMode = DisplayMode.View;
            }

            return View(model);
        }

        public ActionResult ViewIndividualDetails()
        {
            CustomerViewModel model = (IndividualCustomerViewModel) TempData["CustomerDetailModel"];
            if (model == null)
            {
                ICustomerVO customer = (IIndividualCustomerVO)Session["SessionCustomer"];
                if (customer != null)
                {
                    model = (IndividualCustomerViewModel)
                        CustomerMapper.Map(customer, typeof(IIndividualCustomerVO), typeof(IndividualCustomerViewModel));
                    TempData["CustomerDetailModel"] = model;
                }
            }

            PrepareOptionsList(CustomerType.Individual);
            ViewBag.DisplayMode = DisplayMode.Edit;
            if (User.IsInRole(Constants.GetEnumDescription(UserRole.CA)))
            {
                ViewBag.DisplayMode = DisplayMode.View;
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveCompanyCustomer(CompanyCustomerViewModel model, ActionType actionType)
        {
            Logger.Debug("SaveCompanyCustomer|Action type: " + actionType);

            if (actionType == ActionType.Save)
            {
                try
                {
                    if (CustomerBO.CheckIfIdCombinationExists(
                        Int32.Parse(model.IdType), model.IdNumber, model.IdIssuedCountry, model.Id))
                    {
                        TempData["MessageType"] = MessageType.Error;
                        TempData["MessageDescription"] = CommonResources.MessageIdAlreadyExists;

                        TempData["CustomerDetailModel"] = model;
                        return RedirectToAction("ViewCustomerDetails");
                    }

ClosDotNet/Controllers/TaskController.cs
namespace ClosDotNet.Controllers
{
    using ClosDotNet.Domain.CallReport;
    using ClosDotNet.Domain.Task;
    using ClosDotNet.Helper;
    using ClosDotNet.Mapper;
    using ClosDotNet.Models;
    using System.Collections.Generic;
    using System.Web.Mvc;

    [Authorize]
    public class TaskController : Controller
    {
        public ITaskBO TaskBO { get; set; }
        public IMapper TaskMapper { get; set; }

        public ActionResult ViewTaskCallReportList(TaskViewType viewType)
        {
            IList<CallReportTaskViewModel> modelList = new List<CallReportTaskViewModel>();
            IList<ICallReportVO> taskList = null;                
            if (viewType == TaskViewType.Draft)
            {
                taskList = TaskBO.RetrieveCallReportTaskList(User.Identity.Name, true);
                ViewBag.ActiveSubSubMenu = "TaskDraftCallReport";
            }
            else
            {
                taskList = TaskBO.RetrieveCallReportTaskList(User.Identity.Name, false);
                ViewBag.ActiveSubSubMenu = "TaskSubmittedCallReport";
            }

            if (taskList != null)
            {
                modelList = (IList<CallReportTaskViewModel>) TaskMapper.Map(
                    taskList, typeof(IList<ICallReportVO>), typeof(IList<CallReportTaskViewModel>));
            }

            return View(modelList);
        }
    }
}

ClosDotNet/Views/Shared/Message.cshtml
@using System;
@using ClosDotNet.Helper;

@{
    ViewBag.Title = "Message";
}

<div class="col-md-12">
    @if (TempData["MessageDescription"] != null)
    {
        if ((MessageType) TempData["MessageType"] == MessageType.Error)
        {
            <div class="alert alert-danger" role="alert">
                @TempData["MessageDescription"]
            </div>
        }
        else
        {
            <div class="alert alert-info" role="alert">
                @TempData["MessageDescription"]
            </div>
        }
    }
</div>

ClosDotNet/Views/Shared/_FooterPartial.cshtml
@using Microsoft.AspNet.Identity
@using System.Web.Security;
@using ClosDotNet.Resources.Resources;

@if (!Request.IsAuthenticated)
{
    <div class="container">
        <br />
        <footer>
            <p class="copyright">
                @LoginResources.Copyright
            </p>
        </footer>
    </div>
}

ClosDotNet/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

ClosDotNet/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

ClosDotNet/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNet.Identity
@using System.Web.Security;
@using ClosDotNet.Resources.Resources;

@if (Request.IsAuthenticated)
{
    <table class="header banner">
        <tr>
            <td rowspan="2" class="text-left">
                <img src="~/Resources/Images/logo.png" />
            </td>
            <td class="text-right" style="padding-right: 15px;">
                @User.Identity.Name
                |
                @(Roles.IsUserInRole("CA") ? CommonResources.RoleDescriptionCA : "")
                @(Roles.IsUserInRole("RMTL") ? CommonResources.RoleDescriptionRMTL : "")
                @(Roles.IsUserInRole("RM") ? CommonResources.RoleDescriptionRM : "")
                |
                Version @typeof(ClosDotNet.MvcApplication).Assembly.GetName().Version
                |
                @DateTime.Now.ToString()
            </td>
        </tr>
        <tr>
            <td style="padding-right: 15px;">
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right  icon" }))
                {
                    @Html.AntiForgeryToken()
                    <a href="javascript:document.getElementById('logoutForm').submit()">
                        <img src="~/Resources/Images/logout.gif" />
                    </a>
                }
                <div class="navbar-right icon">
                    <a href="@Url.Action("Welcome", "Home")">
                        <img src="~/Resources/Images/home.gif" />
                    </a>
                </div>
                <div class="navbar-right icon">
                    <a href="@Url.Action("Search", "Customer")">
                        <img src="~/Resources/Images/search.gif" />
                    </a>
                </div>
            </td>
        </tr>
    </table>
}

@Html.Partial("_MenuPartial")

ClosDotNet/Views/Shared/_Layout.cshtml
@using ClosDotNet.Resources.Resources;

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@ViewBag.Title - @CommonResources.ApplicationName</title>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <table id="mainContainer">
        <tr>
            <td>
                @Html.Partial("_HeaderPartial")
            </td>
        </tr>
        <tr>
            <td style="height: 100%;">
                <div class="container-fluid body-content">
                    @RenderBody()        
                </div>
                <br />
            </td>
        </tr>
        <tr>
            <td>@Html.Partial("_FooterPartial")</td>
        </tr>
    </table> 

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/gridmvc")
    @Scripts.Render("~/bundles/smartlender")
    @RenderSection("scripts", required: false)

    <div class="fullscreensilk" id="fullscreensilk" style="display:none;">
        <table style="width: 100%; height: 100%; background-color: #F5F5F5; padding: 0px; border-spacing: 0px;">
            <tr>
                <td align="center" valign="middle">
                    <div class="fullscreensilk" id="fullscreensilkimage">
                        <div id="spinLoading">
                            <img src="~/Resources/Images/loading.gif" border="0" />
                            <div id="loading-message" style="display: none; margin-bottom: 10px;"></div>
                            <div id="loading-count" style="display: block; margin-bottom: 4px;"></div>
                        </div>
                    </div>&nbsp;
                </td>
            </tr>
        </table>
    </div>
    <script type="text/javascript">
        $(window).bind('beforeunload', function () {
            setUnloadFlag();
        });

        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
            todayHighlight: true
        });

        $(".yearpicker").datepicker({
            format: ' yyyy', // Do not remove the extra space.
            viewMode: 'years',
            minViewMode: 'years'
        });
    </script>
</body>

</html>

ClosDotNet/Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNet.Identity
@using System.Web.Security;
@using ClosDotNet.Domain.Customer;
@using ClosDotNet.Helper;
@using ClosDotNet.Resources.Resources;

@if (Request.IsAuthenticated)
{
    <div id="tabbar-menu" class="tab-menu">
        <!-- TaskCreditOrigination : Level 1 -->
        @if (ViewBag.ActiveMenu == "Home")
        {
            <ul class="nav nav-tabs">
                <li @PrintClass(ViewBag.ActiveSubMenu, "TaskCallReport")>
                    <a href="@Url.Action("ViewTaskCallReportList", "Task", new { viewType = TaskViewType.Draft })">
                        <span class="glyphicon glyphicon-tasks"></span> @MenuResources.CreditOriginationTask</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-tasks"></span> @MenuResources.PostApprovalTask</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-inbox"></span> @MenuResources.Others</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-list-alt"></span> @MenuResources.Diary</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-unchecked"></span> @MenuResources.LeadManagement</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-stats"></span> @MenuResources.BusinessReport</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-picture"></span> @MenuResources.Chart</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-edit"></span> @MenuResources.UDFModule</a></li>
            </ul>
        }

        <!-- TaskCreditOrigination : Level 2 -->
        @if (ViewBag.ActiveSubMenu == "TaskCallReport")
        {
            <ul class="nav nav-tabs">
                <li><a href="#"><span class="glyphicon glyphicon-edit"></span> @MenuResources.Drafts</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-check"></span> @MenuResources.PendingApproval</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-check"></span> @MenuResources.PendingMyApproval</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-transfer"></span> @MenuResources.Return</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-ok"></span> @MenuResources.ApprovedDeclined</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-envelope"></span> @MenuResources.Enquiry</a></li>
                <li @PrintClass(ViewBag.ActiveSubMenu, "TaskCallReport")>
                    <a href="@Url.Action("ViewTaskCallReportList", "Task", new { viewType = TaskViewType.Draft })">
                        <span class="glyphicon glyphicon-th-list"></span> @MenuResources.CallReport</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-file"></span> @MenuResources.TermSheet</a></li>
            </ul>
        }

        <!-- TaskCreditOrigination : Level 3 -->
        @if (ViewBag.ActiveSubMenu == "TaskCallReport")
        {
            <ul class="nav nav-tabs">
                <li @PrintClass(ViewBag.ActiveSubSubMenu, "TaskDraftCallReport")>
                    <a href="@Url.Action("ViewTaskCallReportList", "Task", new { viewType = TaskViewType.Draft })">
                        <span class="glyphicon glyphicon-edit"></span> @MenuResources.Draft</a></li>
                <li @PrintClass(ViewBag.ActiveSubSubMenu, "TaskSubmittedCallReport")>
                    <a href="@Url.Action("ViewTaskCallReportList", "Task", new { viewType = TaskViewType.Submitted })">
                        <span class="glyphicon glyphicon-check"></span> @MenuResources.Submitted</a></li>
            </ul>
        }

        <!-- SearchCustomer : Level 1 -->
        @if (ViewBag.ActiveMenu == "SearchCustomer")
        {
            <ul class="nav nav-tabs">
                <li @PrintClass(ViewBag.ActiveMenu, "SearchCustomer")>
                    <a href="@Url.Action("Search", "Customer")">
                        <span class="glyphicon glyphicon-search"></span> @MenuResources.CustomerSearch</a></li>
            </ul>
        }

        @{ ICustomerVO customer = (ICustomerVO)Session["SessionCustomer"]; }
        <!-- Customer : Level 1 -->
        @if (ViewBag.ActiveMenu == "Customer")
        {
            <ul class="nav nav-tabs">
                <li @PrintClass(ViewBag.ActiveMenu, "Customer")>
                    <a href="@Url.Action("ViewCustomer", "Customer", new { customerType = customer.CustomerType})">
                        <span class="glyphicon glyphicon-user"></span> @MenuResources.Customer
                    </a></li>
            </ul>
        }

        <!-- Customer : Level 2 -->
        @if (ViewBag.ActiveMenu == "Customer")
        {
            <ul class="nav nav-tabs">
                <li @PrintClass(ViewBag.ActiveSubMenu, "CustomerDetails")>
                    <a href="@Url.Action("ViewCustomer", "Customer", new { customerType = customer.CustomerType})">
                        <span class="glyphicon glyphicon-user"></span> @MenuResources.CustomerDetails</a></li>
                @if (customer.Id != 0)
                {
                    if (UIUtility.IsCompanyCustomer(customer)) { 
                        <li @PrintClass(ViewBag.ActiveSubMenu, "CustomerBusiness")>
                            <a href="@Url.Action("ViewBusiness", "Business", new { customerType = customer.CustomerType})">
                                <span class="glyphicon glyphicon-briefcase"></span> @MenuResources.Business
                            </a></li>
                    }
                    <li @PrintClass(ViewBag.ActiveSubMenu, "CustomerCallReport")>
                        <a href="@Url.Action("ViewCallReportList", "CallReport")">
                            <span class="glyphicon glyphicon-phone"></span> @MenuResources.CallReport</a></li>
                }
            </ul>
        }
    </div>
}

@helper PrintClass(string activeMenu, string actualMenu)
{
    if (activeMenu == actualMenu)
    { 
        <text>class='active'</text>
    }
}