ClosDotNet/Models/CallReportViewModel.cs
namespace ClosDotNet.Models
{
    using ClosDotNet.Resources.Resources;
    using Foolproof;
    using System.ComponentModel.DataAnnotations;

    public class ListCallReportViewModel
    {
        public int Id { get; set; }

        public string ReferenceNo { get; set; }

        public string CallPurpose { get; set; }

        public string CallDate { get; set; }

        public string Originator { get; set; }

        public string LastUpdateDate { get; set; }

        public string CurrentRecipient { get; set; }

        public string Status { get; set; }

        public string Workflow { get; set; }
    }

    public class CallReportViewModel
    {
        public int Id { get; set; }

        [Display(Name = "LabelReportDetailCustomerName", ResourceType = typeof(CallReportResources))]
        public string CustomerName { get; set; }

        [Display(Name = "LabelReportDetailReferenceNo", ResourceType = typeof(CallReportResources))]
        public string ReferenceNo { get; set; }

        [Display(Name = "LabelReportDetailPreviousCallDate", ResourceType = typeof(CallReportResources))]
        public string PreviousCallDate { get; set; }
        
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "LabelReportDetailCallDate", ResourceType = typeof(CallReportResources))]
        public string CallDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "LabelReportDetailSiteVisitDate", ResourceType = typeof(CallReportResources))]
        public string SiteVisitDate { get; set; }

        [Required]
        [Display(Name = "LabelReportDetailContactMode", ResourceType = typeof(CallReportResources))]
        public char ContactMode { get; set; }

        [Required]
        [Display(Name = "LabelReportDetailCallPurpose", ResourceType = typeof(CallReportResources))]
        public int CallPurpose { get; set; }

        [StringLength(1000)]
        [Display(Name = "LabelReportDetailAdditionalPurpose", ResourceType = typeof(CallReportResources))]
        public string Purpose { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = "LabelReportDetailAttendees", ResourceType = typeof(CallReportResources))]
        public string Attendees { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = "LabelReportDetailFollowUp", ResourceType = typeof(CallReportResources))]
        public string FollowUp { get; set; }
        
        #region Submit Section
        [Required]
        [Display(Name = "LabelReportSubmitAction", ResourceType = typeof(CallReportResources))]
        public string Action { get; set; }

        [RequiredIf("Action", "Submit",
            ErrorMessageResourceName = "MessageRequiredField",
            ErrorMessageResourceType = typeof(CommonResources))]
        [Display(Name = "LabelReportSubmitReviewer", ResourceType = typeof(CallReportResources))]
        public string ReviewerId { get; set; }
        #endregion Submit Section
    }
}

ClosDotNet/Controllers/CallReportController.cs
namespace ClosDotNet.Controllers
{
    using ClosDotNet.Domain.CallReport;
    using ClosDotNet.Domain.CodeSet;
    using ClosDotNet.Domain.Customer;
    using ClosDotNet.Domain.User;
    using ClosDotNet.Domain.Util;
    using ClosDotNet.Helper;
    using ClosDotNet.Mapper;
    using ClosDotNet.Models;
    using ClosDotNet.Resources.Resources;
    using Common.Logging;
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    [Authorize]
    public class CallReportController : CommonController
    {
        private static readonly ILog Logger = LogManager.GetLogger(typeof(CustomerController));

        public ICustomerBO CustomerBO { get; set; }
        public ICallReportManager CallReportManager { get; set; }
        public IMapper CallReportMapper { get; set; }

        public ActionResult ViewCallReportList()
        {
            ClearSessionData();

            IEnumerable<ListCallReportViewModel> resultModel = new List<ListCallReportViewModel>();

            ICustomerVO sessionCustomer = (ICustomerVO) Session["SessionCustomer"];
            if (sessionCustomer != null)
            {
                IList<ICallReportVO> callReportList = CallReportManager.RetrieveCallReportsByCustomerId(sessionCustomer.Id);

                resultModel = (IEnumerable<ListCallReportViewModel>)
                    CallReportMapper.Map(callReportList, 
                    typeof(IList<ICallReportVO>), 
                    typeof(IEnumerable<ListCallReportViewModel>));
            }

            return View(resultModel);
        }

        public ActionResult ViewCallReport(int callReportId)
        {
            Logger.Debug("ViewCallReport|Selected Call Report ID: " + callReportId);

            CallReportViewModel model = null;
            if (callReportId != 0)
            {
                ICallReportVO callReport = CallReportManager.RetrieveCallReport(callReportId);
                if (callReport != null)
                {
                    model = (CallReportViewModel)
                        CallReportMapper.Map(callReport, typeof(ICallReportVO), typeof(CallReportViewModel));
                    Session["SessionCallReport"] = callReport;

                    if (Session["SessionCustomer"] == null)
                    {
                        if (Constants.GetEnumDescription(CustomerType.Individual).Equals(callReport.Customer.CustomerType))
                        {
                            Session["SessionCustomer"] =
                                (IIndividualCustomerVO)CustomerBO.RetrieveIndividualCustomer(callReport.Customer.Id);
                        }
                        else
                        {
                            Session["SessionCustomer"] =
                                (ICompanyCustomerVO)CustomerBO.RetrieveCompanyCustomer(callReport.Customer.Id);
                        }
                    }
                }

            }

            if (model == null)
            {
                ICustomerVO sessionCustomer = (ICustomerVO) Session["SessionCustomer"];

                model = new CallReportViewModel();
                model.CustomerName = sessionCustomer.CustomerName;
            }

            // Needed to do this so that the client validation will not trigger.
            TempData["CallReportDetailModel"] = model;
            return RedirectToAction("ViewCallReportDetails");
        }

        public ActionResult ViewCallReportDetails()
        {
            ICallReportVO sessionCallReport = (ICallReportVO) Session["SessionCallReport"];
            CallReportViewModel model = (CallReportViewModel) TempData["CallReportDetailModel"];

            ViewBag.CallPurposeList = GetDropdownList(CodeSetCode.CALL_PURPOSE, CallReportMapper);
            ViewBag.ReviewerList = GetUserList(new string[] { User.Identity.Name });
            ViewBag.ActionList = GetActionList(sessionCallReport != null ? sessionCallReport.WorkflowProcessId : null);
            ViewBag.DisplayMode = DisplayMode.Edit;

            if (sessionCallReport != null && !string.IsNullOrEmpty(sessionCallReport.TaskStatus)
                && ("COMPLETED".Equals(sessionCallReport.TaskStatus) 
                    || (sessionCallReport.CurrentRecipient != null 
                        && !User.Identity.Name.Equals(sessionCallReport.CurrentRecipient.LoginId))))
            {
                ViewBag.DisplayMode = DisplayMode.View;
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProcessCallReport(CallReportViewModel model, ActionType actionType)
        {
            Logger.Debug("SaveCallReport|Action type: " + actionType);

            if (actionType == ActionType.Process)
            {
                try
                {
                    ICallReportVO callReport = (CallReportVO)
                        CallReportMapper.Map(model, typeof(CallReportViewModel), typeof(CallReportVO));

                    ICallReportVO sessionCallReport = (ICallReportVO) Session["SessionCallReport"];
                    if (callReport.Id == 0 || sessionCallReport == null)
                    {
                        sessionCallReport = new CallReportVO();
                    }

                    AccessorUtil.copyValue(callReport, sessionCallReport, CallReportVO.EXCLUDE_COPY);

                    sessionCallReport.LastUpdateBy = User.Identity.Name;

                    ICustomerVO sessionCustomer = (ICustomerVO) Session["SessionCustomer"];
                    sessionCallReport.Customer = sessionCustomer;

                    sessionCallReport = CallReportManager.ProcessCallReport(sessionCallReport, model.Action);

                    model = (CallReportViewModel)
                        CallReportMapper.Map(sessionCallReport, typeof(ICallReportVO), typeof(CallReportViewModel));

                    Session["SessionCallReport"] = sessionCallReport;
                    TempData["MessageType"] = MessageType.Success;
                    TempData["MessageDescription"] = CommonResources.MessageSaveSuccess;
                } 
                catch (Exception exception)
                {
                    Logger.Debug("Exception encountered: " + exception.StackTrace);

                    TempData["MessageType"] = MessageType.Error;
                    TempData["MessageDescription"] = CommonResources.MessageSaveError + exception.Message;
                }

                TempData["CallReportDetailModel"] = model;
                return RedirectToAction("ViewCallReportDetails");
            }

            return RedirectToAction("ViewCallReportList");
        }

        #region Utility Methods
        private IList<SelectListItem> GetActionList(Guid? processId)
        {
            IList<IActionTypeVO> actionList = CallReportManager.RetrieveActionList(processId);
            Logger.Debug("Search|Action DDL: " + (actionList != null ? actionList : null));

            return (IList<SelectListItem>)
                CallReportMapper.Map(actionList, typeof(IList<IActionTypeVO>), typeof(IList<SelectListItem>));
        }

        private IList<SelectListItem> GetUserList(IList<string> excludedUserLoginIdList)
        {
            IList<IUserVO> userList = CallReportManager.RetrieveUserList(excludedUserLoginIdList);
            Logger.Debug("Search|User DDL: " + (userList != null ? userList : null));

            return (IList<SelectListItem>)
                CallReportMapper.Map(userList, typeof(IList<IUserVO>), typeof(IList<SelectListItem>));
        }

        private void ClearSessionData()
        {
            Session["SessionCallReport"] = null;
        }
        #endregion Utility Methods
    }
}

ClosDotNet/Views/CallReport/ViewCallReportDetails.cshtml
@using ClosDotNet.Resources.Resources;

@model ClosDotNet.Models.CallReportViewModel

@{
    ViewBag.Title = CallReportResources.TitleCallReportDetails;
    ViewBag.ActiveMenu = "Customer";
    ViewBag.ActiveSubMenu = "CustomerCallReport";
}

@using (Html.BeginForm("ProcessCallReport", "CallReport", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("Message")

    <fieldset>
        <legend>@CallReportResources.TitleCallReportDetails</legend>

        <section id="callReportForm">                
            <table class="table table-bordered table-condensed">
                <tr>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.CustomerName, new { @class = "control-label" })
                    </td>
                    <td class="fieldvalue">
                        @Html.DisplayFor(m => m.CustomerName, new { @class = "form-control input-sm" })
                        @Html.HiddenFor(m => m.CustomerName)
                    </td>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.ReferenceNo, new { @class = "control-label" })
                    </td>
                    <td class="fieldvalue">
                        @Html.DisplayFor(m => m.ReferenceNo, new { @class = "form-control input-sm" })
                        @Html.HiddenFor(m => m.ReferenceNo)
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.CallDate, new { @class = "control-label" })
                    </td>
                    <td>
                        @Html.TextBoxFor(m => m.CallDate, new { @class = "form-control input-sm datepicker" })
                        @Html.ValidationMessageFor(m => m.CallDate, "", new { @class = "text-danger" })
                    </td>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.SiteVisitDate, new { @class = "control-label" })
                    </td>
                    <td>
                        @Html.TextBoxFor(m => m.SiteVisitDate, new { @class = "form-control input-sm datepicker" })
                        @Html.ValidationMessageFor(m => m.SiteVisitDate, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.ContactMode, new { @class = "control-label" })
                    </td>
                    <td>
                        @Html.RadioButtonFor(m => m.ContactMode, "I") @CallReportResources.OptionContactModeByPhone <br />
                        @Html.RadioButtonFor(m => m.ContactMode, "C") @CallReportResources.OptionContactModeAtBank <br />
                        @Html.RadioButtonFor(m => m.ContactMode, "N") @CallReportResources.OptionContactModeAtClientOffice <br />
                        @Html.RadioButtonFor(m => m.ContactMode, "O") @CallReportResources.OptionContactModeOtherLocation <br />
                        @Html.ValidationMessageFor(m => m.ContactMode, "", new { @class = "text-danger" })
                    </td>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.CallPurpose, new { @class = "control-label" })
                    </td>
                    <td>
                        @Html.DropDownListFor(
                            m => m.CallPurpose, 
                            (IList<SelectListItem>) ViewBag.CallPurposeList, 
                            CommonResources.OptionPleaseSelect, 
                            new { @class = "form-control input-sm" })
                        @Html.ValidationMessageFor(m => m.CallPurpose, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.Purpose, new { @class = "control-label" })
                    </td>
                    <td colspan="3">
                        @Html.TextAreaFor(m => m.Purpose, new { @class = "form-control input-sm", @rows = "5" })
                        @Html.ValidationMessageFor(m => m.Purpose, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.Attendees, new { @class = "control-label" })
                    </td>
                    <td colspan="3">
                        @Html.TextAreaFor(m => m.Attendees, new { @class = "form-control input-sm", @rows = "5" })
                        @Html.ValidationMessageFor(m => m.Attendees, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.FollowUp, new { @class = "control-label" })
                    </td>
                    <td colspan="3">
                        @Html.TextAreaFor(m => m.FollowUp, new { @class = "form-control input-sm", @rows = "5" })
                        @Html.ValidationMessageFor(m => m.FollowUp, "", new { @class = "text-danger" })
                    </td>
                </tr>
            </table>                
        </section>
    </fieldset>

    <fieldset>
        <legend>@CallReportResources.SubTitleSubmit</legend>

        <section id="callReportForm">                
            <table class="table table-bordered table-condensed">
                <tr>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.Action, new { @class = "control-label" })
                    </td>
                    <td class="fieldvalue">
                        @Html.DropDownListFor(
                            m => m.Action,
                            (IList<SelectListItem>)ViewBag.ActionList,
                            CommonResources.OptionPleaseSelect,
                            new { @class = "form-control input-sm" })
                        @Html.ValidationMessageFor(m => m.Action, "", new { @class = "text-danger" })
                    </td>
                    <td class="fieldname">
                        @Html.LabelFor(m => m.ReviewerId, new { @class = "control-label" })
                    </td>
                    <td class="fieldvalue">
                        @Html.DropDownListFor(
                            m => m.ReviewerId,
                            (IList<SelectListItem>)ViewBag.ReviewerList,
                            CommonResources.OptionPleaseSelect,
                            new { @class = "form-control input-sm" })
                        @Html.ValidationMessageFor(m => m.ReviewerId, "", new { @class = "text-danger" })
                    </td>

                </tr>
            </table>
        </section>
    </fieldset>
    
    <div class="form-group">
        <div class="col-sm-12 text-center">
            <br />
            @Html.HiddenFor(m => m.Id)
            
            <input type="submit" name="actionType" value="@CommonResources.ButtonProcess" class="btn btn-default btn-sm" />
            <input type="submit" name="actionType" value="@CommonResources.ButtonCancel" class="btn btn-default btn-sm cancel" />
        </div>
    </div>
}
    
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/foolproof")

    <script type="text/javascript">
    $(function () {
        @if (ViewBag.DisplayMode == ClosDotNet.Helper.DisplayMode.View)
        {
            <text>
            prepareCheckerMode();
            </text>
        }
    });
    </script>
}

ClosDotNet/Views/CallReport/ViewCallReportList.cshtml
@using ClosDotNet.Helper;
@using ClosDotNet.Resources.Resources;
@using GridMvc.Html
@using System.Linq

@model IEnumerable<ClosDotNet.Models.ListCallReportViewModel>

@{
    ViewBag.Title = CallReportResources.TitleReportList;
    ViewBag.ActiveMenu = "Customer";
    ViewBag.ActiveSubMenu = "CustomerCallReport";
}

@Styles.Render("~/Content/gridmvc")


<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("ViewCallReport", "CallReport", new { callReportId = 0 }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {            
            <table>
                <tr>
                    <td><h4>@CallReportResources.TitleReportList</h4></td>
                    <td class="text-right">
                        @if (!Roles.IsUserInRole("CA"))
                        {
                            <input type="submit" name="actionType" value="@CommonResources.ButtonAddNew" class="btn btn-default btn-sm" />
                        }
                    </td>
                </tr>
            </table>
        }        
        <hr />

        @{ int rowNumber = 0; }
        @Html.Grid(Model).Columns(columns =>
            {
                columns.Add().Titled(CommonResources.LabelRowNumber)
                    .Sanitized(false).Encoded(false)
                    .RenderValueAs(o =>
                    {
                        rowNumber++;
                        return UIUtility.RenderRowNumber(Request.QueryString["grid-page"], 10, rowNumber);
                    })
                    .Css("index");
                columns.Add(c => c.ReferenceNo).Titled(CallReportResources.LabelReportListRefNo)
                    .Sanitized(false).Encoded(false)
                    .RenderValueAs(c => Html.ActionLink(c.ReferenceNo, "ViewCallReport", new { callReportId = c.Id })
                    .ToHtmlString());
                columns.Add(c => c.CallPurpose).Titled(CallReportResources.LabelReportListCallPurpose);
                columns.Add(c => c.CallDate).Titled(CallReportResources.LabelReportListCallDate);
                columns.Add(c => c.Originator).Titled(CallReportResources.LabelReportListOriginator);
                columns.Add(c => c.LastUpdateDate).Titled(CallReportResources.LabelReportListLastUpdatedDate);
                columns.Add(c => c.CurrentRecipient).Titled(CallReportResources.LabelReportCurrentRecipient);
                columns.Add(c => c.Status).Titled(CallReportResources.LabelReportListStatus);
                columns.Add(c => c.Workflow).Titled(CallReportResources.LabelReportListWorkflow);
            }).WithPaging(10)
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/gridmvc")
}